use_frameworks!

platform :ios, '9.0'

target 'YFCommonView_Example' do
  pod 'YFCommonView', :path => '../'
#  pod 'Masonry', '~> 1.1.0'
  
  target 'YFCommonView_Tests' do
    inherit! :search_paths

    
  end
end
